os: linux
dist: xenial

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse --short HEAD)

before_install:
	- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
	- docker build -t $DOCKER_USERNAME/foo-test .

script:
	- docker run -e CI=true $DOCKER_USERNAME/foo-test npm -- --coverage

deploy:
  provider: script
  script: sh deploy.sh
  on:
    branch: master
